insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());
insert into tb_category(NAME, created_AT) values ('Books', NOW());
insert into tb_category(NAME, created_AT) values ('Eletronics',NOW());
insert into tb_category(NAME, created_AT) values ('Computers',NOW());

